[FIX] Processing checkpoint blocks by fetcher
input-output-hk/etc-client pull request #866
Opened 2020-12-21 14:53 UTC by pslaski

# Description

Currently, the fetcher is not processing new checkpoint blocks which are older than the current top

# Important Changes Introduced

- changed processing of lastBlock in BlockFetcherState (reflects the last block imported by blockchain)
- added processing checkpoint blocks by BlockFetcher

# Testing

Syncing with Mordor testnet in progress.
Need to be tested with federation nodes.

2020-12-22 09:04 UTC, kapke requested changes

2020-12-22 09:04 UTC, kapke commented on src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
> +    if (state.waitingHeaders.exists(_.hash == block.hash || state.readyBlocks.exists(_.hash == block.hash))) {
I think it would be quite beneficial to:
1. extract methods for checking headers and blocks existence by hash (in fetcher state)
2. save results to variables here, so computation is not performed with each `if`

2020-12-22 09:04 UTC, kapke commented on src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
> +        val newState = state
shouldn't the block be saved somehow or passed to block importer in this case? This case means more or less "we're on different fork" and we don't do anything in order to switch into checkpointed branch

2020-12-22 09:04 UTC, kapke commented on src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
> +      } else handleFutureBlock(block, state)
Same here - we just try to update known top block and believe other nodes will do their job so we land on checkpointed branch.
If this code doesn't fork on checkpointed testnet - we can probably leave it as it is now and pass a follow-up task to the team. WDYT?

2020-12-22 09:04 UTC, kapke commented on src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
> +        val newState = state
For inserting checkpoint into right slot - please make and use methods that protect fetcher state invariants (like for headers there's `appendHeaders`)
It could probably even simplify the code here significantly to something in lines of:
```
state.tryInsertCheckpointBlock(block, peerId) match {
  case Left(err) if block.number <= state.lastBlock =>
    log.debug("Couldn't insert checkpoint to queues, passing to importer")
    state.importer ! NewCheckpointBlock(block, peerId)
  case Left(err) =>
    log.debug("Couldn't insert checkpoint to queues")
    //whatever
  case Right(newState) =>
    fetchBlocks(newState)
}
```

2020-12-22 09:04 UTC, kapke commented on src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherState.scala
> +  def enqueueHeader(header: BlockHeader): BlockFetcherState = {
please remove these methods and use safer counterparts - lack of them caused a bit of headache already

2020-12-22 09:04 UTC, kapke commented on src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherSpec.scala
> +      startFetcher()
does it make sense to extract some common parts from these tests?

2020-12-23 09:51 UTC, kapke approved these changes
Minor things, besides that looks good to me!

2020-12-23 09:51 UTC, kapke commented on src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherState.scala
> +    if (isExistInReadyBlocks(blockHash) || isExistInWaitingHeaders(blockHash)) {
just `exists`?

2020-12-23 09:51 UTC, kapke commented on src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherSpec.scala
> +      importer.send(blockFetcher, PickBlocks(firstBlocksBatch.size))
isn't this `send` call duplicate now?

2020-12-23 16:27 UTC, lemastero approved these changes

2021-01-05 11:29 UTC, merged